echo "Running swift bill application"

start  /B /wait cmd /c "npm install -g npx"
start  /B /wait cmd /c "npm install -g kill-port"
start  /B /wait cmd /c "npx kill-port 3000"
start  /B /wait cmd /c "npx kill-port 8000"
cd "swift-bill-app"
start  /B /wait cmd /c "npm install --frozen-lock"
cd "..\swift-bill-server"
start /B /wait cmd /c "npm install --frozen-lock"
cd ".."
start /B /D "swift-bill-app" cmd /c "npm start"
start /B /D "swift-bill-server" cmd /c "npm start"